== kafka-manager

This is a packaging of link:https://github.com/yahoo/kafka-manager[YAHOO!'s Kafka Manager] in an Alpine based  Docker container

=== Environment variables

`KAFKA_MANAGER_AUTH_ENABLED`:: A boolean, if set to `true` then the manager will be secured with basic authentication.

`KAFKA_MANAGER_USERNAME`:: A string, the username to use for basic auth. Defaults to `admin`

`KAFKA_MANAGER_PASSWORD`:: A string, the passworid to use for basic auth. Defaults to `password`

`ZK_HOSTS`:: A string, the comma separated `host:port` list of the ZooKeeper Quorum. Defaults to `kafka-manager-zookeeper:2181`

`APPLICATION_SECRET`:: A string, the secret key used to secure cryptographic functions in the Play! framework that Kafka Manager is built with.

`CONSUMER_PROPERTIES_FILE`:: A file path, _I don't know what this does yet!!!_

`KM_ADD_CLUSTER`:: A string, if provided then on first start-up the supplied cluster will be seeded using the JSON file at `/opt/cluster-template.json`.
+
The string is expected to be of the form `CLUSTER_NAME=CLUSTER_ZOOKEEPER`, for example `example=kafka-zookeeper1:2181/acme,kafka-zookeeper2:2181/acme,kafka-zookeeper3:2181/acme`

